=== MaxTsikhamirau/JavaRepository/tikhomirov/src/lab37_39/example.dtd
<!DOCTYPE pointList
        [
                <!ELEMENT pointList (point*)>
                <!ELEMENT point (x,y,unit)>
                <!ELEMENT x (#PCDATA)>
                <!ELEMENT y (#PCDATA)>
                <!ELEMENT unit (#PCDATA)>
                ]>

=== MaxTsikhamirau/JavaRepository/tikhomirov/src/lab37_39/example_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pointList SYSTEM "example.dtd">
<pointList>
    <point>
        <x>2</x>
        <y>5</y>
    </point>

    <point>
        <x>2</x>
        <y>5</y>
        <unit>mm</unit>
    </point>

</pointList>
